apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: w5dp0n4gm-nodejs 
  janus-idp.io/tekton: w5dp0n4gm-nodejs
  backstage.io/kubernetes-id: w5dp0n4gm-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w5dp0n4gm-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml